# Generated by Django 5.0.3 on 2024-07-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
